version: "3.7"
services:
  countries:
    image: lamersons/countries-assembly:${RELEASE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/health/ready"]
      # start_period: 30s
      interval: 5s
      timeout: 10s
      retries: 20
    deploy:
      labels:
        com.docker.stack.namespace: countries-assembly:${RELEASE}
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 30
        window: 120s
    networks:
      - "default"
networks:
    default:
        external:
            name: countries
#     networks:
#       - "countries_overlay"
#
# networks:
#   countries_overlay:
#     name: countries
#     driver: "overlay"
#     attachable: true
#     internal: true
#     ipam:
#      config:
#        - subnet: 10.11.0.0/16