version: "3.7"
services:
  jenkins:
    image: jenkinsci/blueocean
    healthcheck:
      disable: true
    volumes:
      - type: bind
        source: /hosthome/shared_drive/jenkins_home/
        target: /var/jenkins_home
      - type: bind
        source: /hosthome/shared_drive/nginx/conf/conf.d
        target: /opt/nginx/conf/conf.d
    deploy:
      labels:
        com.docker.stack.namespace: jenkins
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "9999:8080"