version: "3.7"
services:
  airports:
    # labels:
    #   com.docker.stack.namespace: "watafack"
    image: lamersons/airports-assembly:${RELEASE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/health/ready"]
      # start_period: 30s
      interval: 15s
      # timeout: 10s
      retries: 20
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 30
        window: 120s
    networks:
      - "default"
networks:
    default:
        external:
            name: airports
# networks:
#   airports_overlay:
#     name: airports
    # driver: "overlay"
    # attachable: true
    # internal: true
    # ipam:
    #  config:
    #    - subnet: 10.12.0.0/16