# -*- coding: utf-8 -*-
##############################################################################
# deps: docker-compose > 3.5
# Author: MiZo <misha3@gmail.com>
#
# Lunatech DevOps challenge
#
##############################################################################

version: "3.7"
services:
  nginx:
    image: nginx
    healthcheck:
      disable: true
    volumes:
      - type: bind
        source: /hosthome/shared_drive/nginx/conf
        target: /etc/nginx
    deploy:
      labels:
        com.docker.stack.namespace: nginx
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 30
        window: 120s
    ports:
      - "8000:8000"
    networks:
      - countries_overlay
      - airports_overlay
networks:
  airports_overlay:
    external:
      name: airports
  countries_overlay:
    external:
      name: countries
# networks:
#   countries_overlay:
#     name: countries
#     driver: "overlay"
#     attachable: true
#     internal: true
#     ipam:
#      config:
#        - subnet: 10.11.0.0/16
#   airports_overlay:
#     name: airports
#     driver: "overlay"
#     attachable: true
#     internal: true
#     ipam:
#      config:
#        - subnet: 10.12.0.0/16
